### ISSUE TITLE
你好，请问中级文法可以上传一下到AnkiDeck吗？谢谢

### ISSUE THREAD

**Issue by tshen-PayPay** [wang1zhen/anki-decks#1]

**Comment by wang1zhen** [comment]
中级语法我仅自用做了中级1的部分，中级2还没有做。

**Comment by tshen-PayPay** [comment]
你好，中级语法1也行的，就是不知道该如何导入到Anki里去，谢谢～

**Comment by wang1zhen** [comment]
[链接](https://ankiweb.net/shared/info/8774787?cb=1709045236007)

可能需要24小时候才公开可见。

**Comment by ivysrono** [comment]
期待中级2~
